#!/bin/bash
set -e

hex()
{
	openssl rand -hex 8
}

echo "Preparing container .."
COMMAND="/usr/bin/shellinaboxd --debug --no-beep -u shellinabox -g shellinabox -c /var/lib/shellinabox -p ${SIAB_PORT} --user-css \"${SIAB_USERCSS}\""

if [ "$SIAB_SSL" != "true" ]; then
	COMMAND="${COMMAND} -t"
fi

if [ "${SIAB_ADDUSER}" == "true" ]; then
	sudo=""
	if [ "${SIAB_SUDO}" == "true" ]; then
		sudo="-G sudo"
	fi
	/usr/sbin/useradd -m ${sudo} ${SIAB_USER}
	if [ "${SIAB_PASSWORD}" == "putsafepasswordhere" ]; then
		SIAB_PASSWORD=$(hex)
		echo "Autogenerated password for user ${SIAB_USER}: ${SIAB_PASSWORD}"
	fi
	echo "${SIAB_USER}:${SIAB_PASSWORD}" | /usr/sbin/chpasswd
	unset SIAB_PASSWORD
fi

COMMAND="${COMMAND} -s ${SIAB_SERVICE}"

sed -i "s|__COMMAND__|${COMMAND}|g" /etc/supervisor/conf.d/shellinabox.conf

echo "Starting container .."
if [ "$@" != "shellinabox" ]; then
	exec "$@"
else
	exec /usr/bin/supervisord
fi
